import { describe, expect, it } from 'vitest'
import { EditorState } from '@codemirror/state'
import { highlightingFor } from '@codemirror/language'
import { tags } from '@lezer/highlight'
import { horizonHighlightStyle, horizonSyntaxExtensions } from './crepe.syntax'

/**
 * `horizonHighlightStyle`'s CSS is generated by `style-mod` (via
 * `HighlightStyle.define`) under auto-named classes, so the only way to see
 * what colour a role actually resolves to is to read the generated rule text
 * back out - `.module.getRules()` is `style-mod`'s own accessor for it. This
 * is the same stylesheet CodeMirror injects into the document at runtime.
 */
const generatedCss = () => horizonHighlightStyle.module?.getRules() ?? ''

describe('horizonHighlightStyle', () => {
  it('gives every documented syntax role its own chakra CSS variable', () => {
    const css = generatedCss()

    ;['keyword', 'function', 'type', 'string', 'number', 'operator', 'comment', 'invalid'].forEach(
      (role) => {
        expect(css).toContain(`var(--chakra-colors-code-syntax-${role})`)
      },
    )
  })

  it('has no hardcoded colour literal - every rule resolves through a CSS variable', () => {
    // A regression guard against ever reintroducing a fixed palette (One
    // Dark or otherwise): every declaration this style emits must be a
    // `var(...)` reference, never a literal hex/rgb value.
    const css = generatedCss()
    const colorDeclarations = css.match(/color:[^;}]+/g) ?? []

    expect(colorDeclarations.length).toBeGreaterThan(0)
    colorDeclarations.forEach((declaration) => {
      expect(declaration).toMatch(/^color:\s*var\(--chakra-colors-code-syntax-[a-z]+\)$/)
    })
  })
})

describe('horizonSyntaxExtensions', () => {
  it('builds a usable CodeMirror extension', () => {
    // `Prec.highest` returns an opaque wrapper class, not a plain object or
    // array - `EditorState.create` accepting it without throwing is the
    // externally observable proof that CodeMirror's extension flattening
    // still recognises it (see the root-cause note in `CrepeEditor.tsx`).
    expect(() => EditorState.create({ extensions: horizonSyntaxExtensions() })).not.toThrow()
  })

  it('resolves a real tag to a real class through the Prec-wrapped extension', () => {
    // `highlightingFor` is what CodeMirror's own tree highlighter calls to
    // decide a span's class list; going through `horizonSyntaxExtensions()`
    // (the `Prec.highest(...)` wrapper actually handed to Crepe as `theme`)
    // rather than the bare style is the regression guard - it fails the day
    // `Prec.highest` stops producing something CodeMirror's facet resolution
    // still recognises.
    const state = EditorState.create({ extensions: horizonSyntaxExtensions() })
    const keywordClass = highlightingFor(state, [tags.keyword])
    const commentClass = highlightingFor(state, [tags.comment])

    expect(keywordClass).toBeTruthy()
    expect(commentClass).toBeTruthy()
    // Different roles must resolve to different generated classes - if they
    // collapsed to the same one, every token would render in one colour.
    expect(keywordClass).not.toBe(commentClass)
  })
})

/** Every Lezer tag the design review measured must map to a role, not fall through. */
describe('horizonHighlightStyle tag coverage', () => {
  it('covers the tag families named in the spec', () => {
    const coveredTags = horizonHighlightStyle.specs.flatMap((spec) =>
      Array.isArray(spec.tag) ? spec.tag : [spec.tag],
    )

    expect(coveredTags).toContain(tags.keyword)
    expect(coveredTags).toContain(tags.string)
    expect(coveredTags).toContain(tags.number)
    expect(coveredTags).toContain(tags.operator)
    expect(coveredTags).toContain(tags.invalid)
  })
})
