import { FaArrowUpRightFromSquare, FaDownload, FaGithub, FaLinkedin } from 'react-icons/fa6'
import { CvProfile } from './cv.types'

export const cvProfile: CvProfile = {
  name: 'Tran Tuan Canh',
  title: 'Backend Engineer',
  location: 'Ho Chi Minh City, Vietnam',
  email: 'canhtran210699@gmail.com',
  summary:
    'Backend engineer with strong Python and Django experience building microservices for logistics, analytics, authentication, and shipment performance platforms. Experienced in modular backend design, API modernization, event-driven workflows, and production data systems.',
  competencies: [
    {
      title: 'Backend',
      items: ['Python', 'Django', 'Django Ninja', 'Django REST Framework', 'FastAPI'],
    },
    {
      title: 'Data & Messaging',
      items: ['Kafka', 'PostgreSQL', 'Redis', 'OpenSearch', 'ClickHouse', 'Redshift'],
    },
    {
      title: 'Workflow & Processing',
      items: ['Dagster', 'Scala', 'Flink'],
    },
    {
      title: 'Platform',
      items: ['Docker', 'Helm', 'Kubernetes', 'AWS'],
    },
    {
      title: 'Domains',
      items: ['Logistics intelligence', 'Analytics', 'Authentication', 'Shipment performance'],
    },
    {
      title: 'Architecture',
      items: [
        'API design',
        'Validation',
        'Pydantic',
        'Modular service structure',
        'Service-layer patterns',
      ],
    },
    {
      title: 'Shared Capabilities',
      items: ['Search', 'Data synchronization', 'Feature flags', 'Business-calendar logic'],
    },
    {
      title: 'Delivery',
      items: [
        'Asynchronous processing',
        'Outbox-style publishing',
        'Cross-functional backend delivery',
      ],
    },
  ],
  links: [
    {
      label: 'Export PDF',
      icon: FaDownload,
    },
    {
      label: 'GitHub',
      href: 'https://github.com/connortran216',
      icon: FaGithub,
      isExternal: true,
    },
    {
      label: 'LinkedIn',
      href: 'https://www.linkedin.com/in/c%E1%BA%A3nh-tr%E1%BA%A7n-tu%E1%BA%A5n-b57564162/',
      icon: FaLinkedin,
      isExternal: true,
    },
    {
      label: 'Contact',
      to: '/contact',
      icon: FaArrowUpRightFromSquare,
    },
  ],
  experience: [
    {
      company: 'Parcel Perform',
      role: 'Backend Engineer',
      period: '2023 - Present',
      highlights: [
        'Worked on backend systems across logistics intelligence, analytics, authentication, and shipment performance domains.',
        'Built analytics and reporting capabilities for merchant dashboards, exports, and operational insights.',
        'Contributed to alerting and decision-support systems for performance monitoring and root-cause analysis.',
        'Delivered shipment performance, SLA, search and data synchronization, authentication, authorization, feature-toggle, and business-calendar capabilities used in logistics workflows.',
        'Designed and maintained Python services using Django, Django Ninja, Django REST Framework, and FastAPI.',
        'Built event-driven workflows using Kafka consumers, outbox-style publishing, and asynchronous processing, with PostgreSQL, Redis, OpenSearch, ClickHouse, and Redshift in production.',
        'Contributed to Dagster and Scala/Flink systems while improving API design, validation, modular service structure, and testability with Pydantic, Docker, Helm, Kubernetes, and AWS.',
      ],
      stack: [
        'Python',
        'Django',
        'Django Ninja',
        'Django REST Framework',
        'FastAPI',
        'Kafka',
        'PostgreSQL',
        'Redis',
        'OpenSearch',
        'ClickHouse',
        'Redshift',
        'Dagster',
        'Scala',
        'Flink',
        'Docker',
        'Helm',
        'Kubernetes',
        'AWS',
      ],
    },
    {
      company: 'Think Prompt',
      role: 'Backend Engineer Team Lead',
      period: '2023',
      productionUrl: 'https://bizchat.thinkprompt.com/',
      highlights: [
        'Built the backend for a ChatGPT-like chatbot product, including system architecture, infrastructure setup, and RESTful APIs.',
        'Coordinated between the AI and backend teams to keep communication and delivery aligned.',
        'Managed team execution and supported delivery as backend team lead.',
        'Mentored junior developers on frameworks, tools, debugging, error handling, and troubleshooting.',
      ],
      stack: [
        'Python',
        'FastAPI',
        'Hypercorn',
        'LangChain',
        'Postgres',
        'MongoDB',
        'MinIO',
        'Redis',
        'Nginx',
        'Milvus',
        'Docker',
        'GitLab CI',
        'AWS',
        'On-premise infrastructure',
      ],
    },
    {
      company: 'SSSMarket',
      role: 'Backend Engineer Team Lead',
      period: '01/2022 - 01/2023',
      productionUrl: 'https://www.sssmarket.vn/',
      highlights: [
        'Built and maintained a scalable backend for an e-commerce application, covering system architecture, infrastructure setup, and RESTful APIs.',
        'Provided technical leadership through code reviews and technical guidance for the team.',
        'Served as a key point of contact for the CTO and stakeholders, communicating progress and issues.',
        'Addressed performance and security issues to keep the backend stable and efficient.',
        'Collaborated with cross-functional teams to integrate backend functionality with other application components.',
      ],
      stack: [
        'Python',
        'FastAPI',
        'Hypercorn',
        'SQLAlchemy',
        'Postgres',
        'MongoDB',
        'MinIO',
        'Redis',
        'Nginx',
        'Milvus',
        'Solr',
        'Docker',
        'GitLab CI',
        'AWS',
        'On-premise infrastructure',
      ],
    },
    {
      company: 'Dai Phat Solutions',
      role: 'AI Engineer',
      period: '12/2020 - 01/2022',
      productionUrl: 'https://www.dps.com.vn/vi/products/doanhnghiep#',
      highlights: [
        'Developed and maintained a real-time facial recognition system for attendance checking and CCTV surveillance.',
        'Researched new AI technologies to improve system performance and capabilities.',
        'Implemented features from research findings to improve system accuracy and reliability.',
        'Worked with cross-functional teams to gather requirements and incorporate feedback into system enhancements.',
      ],
      stack: [
        'Python',
        'PyTorch',
        'TensorFlow',
        'OpenCV',
        'MongoDB',
        'Redis',
        'Nginx',
        'Milvus',
        'Kafka',
        'Pulsar',
        'Docker',
        'Jenkins',
      ],
    },
    {
      company: 'HAHALOLO Company',
      role: 'Data Analyst Intern',
      period: '06/2019 - 10/2019',
      highlights: [
        'Built a value table for ranking feeds in a newsfeed system based on user relationships.',
        'Analyzed user relationship data for feed ranking using basic data analysis techniques and regression models.',
        'Used Python, NumPy, and Pandas for data manipulation and analysis.',
        'Worked with team members to incorporate user requirements into the ranking algorithm.',
      ],
      stack: ['Python', 'NumPy', 'Pandas'],
    },
  ],
  projects: [
    {
      title: 'Horizon Blog',
      githubUrl: 'https://github.com/connortran216/horizon-blog',
      description:
        'Personal blog application built with React, TypeScript, and Chakra UI, paired with a Go backend that uses clean architecture, JWT authentication, PostgreSQL, media upload support, and API documentation. The project includes rich text editing, search and filtering, a contact form, and technical documentation.',
      stack: [
        'React',
        'TypeScript',
        'Chakra UI',
        'React Router',
        'Milkdown',
        'Vite',
        'Go',
        'Gin',
        'GORM',
        'PostgreSQL',
        'JWT',
        'Swagger',
        'MinIO',
        'Meilisearch',
        'Docker',
      ],
    },
    {
      title: 'Measurement of fetal head circumference based deep learning on 2D ultrasound images',
      period: '12/2020 - 04/2021',
      githubUrl: 'https://github.com/connortran216/Fetal-Head-Circumferences-HC18',
      publicationUrl:
        'http://vap.ac.vn/Portals/0/TuyenTap/2021/12/22/1ecec417207345d595e011cb434f7fe8/20_FAIR2021_paper_139.pdf',
      description:
        'Built a segmentation system to automatically measure fetal head circumference on 2D ultrasound images. In the HC18 grand challenge, the system achieved a mean absolute difference of 7.15 mm with a standard deviation of 4.33.',
      stack: ['Mask RCNN', 'OpenCV', 'Ellipse approximation of Ramanujan'],
    },
    {
      title: 'Facial Recognition',
      period: '09/2019',
      githubUrl: 'https://github.com/connortran216/Attendace-Cheking-using-Facenet-and-MTCNN',
      description:
        'Built a real-time facial recognition pipeline using MTCNN for face detection, FaceNet for feature extraction, and an SVM classifier for identity classification. The model achieved approximately 90% accuracy.',
      stack: ['MTCNN', 'FaceNet', 'OpenCV', 'SORT'],
    },
  ],
  education: [
    {
      school: 'Ton Duc Thang University',
      degree: 'Bachelor of Science in Computer Science',
      period: '2017 - 2021',
      details: [
        'GPA: 7.53/10.',
        'Relevant coursework: Linear Algebra, Statistic & Probability, Calculus, Machine Learning (GPA: 9.3), Artificial Intelligence (GPA: 8.1).',
        'Strengths: Mathematics, Machine Learning, and Deep Learning.',
      ],
    },
  ],
}
