import { FaArrowUpRightFromSquare, FaDownload, FaGithub, FaLinkedin } from 'react-icons/fa6'
import { CvProfile } from './cv.types'

export const cvProfile: CvProfile = {
  name: 'Tran Tuan Canh',
  title: 'Backend Engineer',
  location: 'Ho Chi Minh City, Vietnam',
  email: 'canhtran210699@gmail.com',
  summary:
    'I am a Backend Engineer focused on building reliable, scalable, and maintainable systems that solve real product and engineering problems.\n\nI enjoy working on backend architecture, distributed systems, data-intensive applications, and production workflows where performance, reliability, clean abstractions, and product impact all matter. I like turning complex engineering problems into practical solutions by understanding the problem deeply, breaking it down clearly, and making thoughtful trade-offs.\n\nBeyond traditional backend engineering, I am especially interested in AI-powered engineering workflows and how AI can help teams design systems, write better technical specifications, build internal tools, and improve developer productivity.\n\nFor me, engineering is not only about writing code. It is about designing systems that can evolve over time, improving them continuously, and pushing myself to become a stronger engineer.',
  competencies: [
    {
      title: 'Backend',
      items: ['Python', 'Django', 'Django Ninja', 'Django REST Framework', 'FastAPI'],
    },
    {
      title: 'Data & Messaging',
      items: ['Kafka', 'PostgreSQL', 'Redis', 'OpenSearch', 'ClickHouse', 'Redshift'],
    },
    {
      title: 'Workflow & Processing',
      items: ['Dagster', 'Scala', 'Flink'],
    },
    {
      title: 'Platform',
      items: ['Docker', 'Helm', 'Kubernetes', 'AWS'],
    },
    {
      title: 'Architecture',
      items: [
        'API design',
        'Validation',
        'Pydantic',
        'Modular service structure',
        'Service-layer patterns',
      ],
    },
    {
      title: 'Shared Capabilities',
      items: ['Search', 'Data synchronization', 'Feature flags', 'Business-calendar logic'],
    },
    {
      title: 'Delivery',
      items: [
        'Asynchronous processing',
        'Outbox-style publishing',
        'Cross-functional backend delivery',
      ],
    },
  ],
  links: [
    {
      label: 'Export PDF',
      icon: FaDownload,
    },
    {
      label: 'Blog',
      href: 'https://blog.connortran.io.vn/',
      icon: FaArrowUpRightFromSquare,
      isExternal: true,
    },
    {
      label: 'GitHub',
      href: 'https://github.com/connortran216',
      icon: FaGithub,
      isExternal: true,
    },
    {
      label: 'LinkedIn',
      href: 'https://www.linkedin.com/in/c%E1%BA%A3nh-tr%E1%BA%A7n-tu%E1%BA%A5n-b57564162/',
      icon: FaLinkedin,
      isExternal: true,
    },
    {
      label: 'Contact',
      to: '/contact',
      icon: FaArrowUpRightFromSquare,
    },
  ],
  experience: [
    {
      company: 'Parcel Perform',
      role: 'Backend Engineer',
      period: '2023 - Present',
      highlights: [
        'Owned the end-to-end delivery of backend services for shipment analytics, alerting, and automated insight generation, writing and reviewing technical designs across all squad-owned services and carrying changes through implementation, deployment, and production monitoring.',
        'Built and maintained real-time SLA metric processing on live parcel events using Flink, Kafka, and outbox-style publishing, helping operations teams and merchants monitor shipment health and carrier performance more reliably.',
        'Improved backend quality across service repositories through code review, test design, and implementation standards, maintaining above 90% test coverage across related repositories.',
        'Migrated nearly all APIs from Django REST Framework to Django Ninja, improving maintainability, schema clarity, validation, and developer experience.',
        'Reduced implementation time for customer inquiries from 3-7 days to 1-2 days by creating Claude Code skills and agents adopted across the team, with reusable workflows, quality guardrails, and review steps.',
        "Reduced technical design drafting from 5-7 days to 2-3 days through Claude Code workflows for Jira epics and CI follow-up; contributed to the company boilerplate and helped the team win first prize in Parcel Perform's AI competition.",
      ],
      stack: [
        'Python',
        'Django',
        'Django Ninja',
        'Django REST Framework',
        'FastAPI',
        'Kafka',
        'PostgreSQL',
        'Redis',
        'OpenSearch',
        'ClickHouse',
        'Redshift',
        'Dagster',
        'Scala',
        'Flink',
        'Docker',
        'Helm',
        'Kubernetes',
        'AWS',
      ],
    },
    {
      company: 'Think Prompt',
      role: 'Backend Engineer Team Lead',
      period: '2023',
      productionUrl: 'https://bizchat.thinkprompt.com/',
      highlights: [
        'Led backend development from inception to a functional prototype for an AI business chatbot, owning the architecture and technical decisions across all non-frontend components.',
        'Managed two backend engineers and coordinated with AI researchers, covering technical design, task assignment, implementation guidance, code review, and release decisions.',
        'Designed and implemented an end-to-end document-processing pipeline that transformed raw source materials into vector embeddings and indexed them for chatbot retrieval.',
        'Built the core APIs, AI integration, storage, caching, and deployment foundation, with implementation support from the backend team.',
      ],
      stack: [
        'Python',
        'FastAPI',
        'Hypercorn',
        'LangChain',
        'Postgres',
        'MongoDB',
        'MinIO',
        'Redis',
        'Nginx',
        'Milvus',
        'Docker',
        'GitLab CI',
        'AWS',
        'On-premise infrastructure',
      ],
    },
    {
      company: 'SSSMarket',
      role: 'Backend Engineer Team Lead',
      period: '01/2022 - 01/2023',
      productionUrl: 'https://www.sssmarket.vn/',
      highlights: [
        'Inherited and refactored the e-commerce backend while supporting platform growth from approximately 300,000 to 1.5 million users, with 700-800 daily active users and campaign traffic peaks of 2,000-3,000 users.',
        'Led two backend engineers, trained and mentored interns and junior engineers, and coordinated with AI, marketing, and sales teams to align technical delivery with business priorities.',
        'Helped turn AI research into production-ready capabilities, including product similarity search, recommendation systems, and virtual clothing try-on.',
        'Improved API throughput from approximately 30 to 50-60 requests per second through asynchronous processing, query optimization, and PostgreSQL read replicas, while introducing explicit API schemas to strengthen validation and data correctness.',
        'Led the migration from AWS to on-premise infrastructure to reduce costs, personally provisioning and maintaining the virtual machines and coordinating production incidents with the CTO and stakeholders.',
      ],
      stack: [
        'Python',
        'FastAPI',
        'Hypercorn',
        'SQLAlchemy',
        'Postgres',
        'MongoDB',
        'MinIO',
        'Redis',
        'Nginx',
        'Milvus',
        'Solr',
        'Docker',
        'GitLab CI',
        'AWS',
        'On-premise infrastructure',
      ],
    },
    {
      company: 'Dai Phat Solutions',
      role: 'AI Engineer',
      period: '12/2020 - 01/2022',
      productionUrl: 'https://www.dps.com.vn/vi/products/doanhnghiep#',
      highlights: [
        "Took an inherited facial-recognition prototype to production readiness within the company's SaaS ecosystem, owning the complete pipeline across detection, recognition, tracking, anti-spoofing, integration, and deployment.",
        'Achieved over 95% recognition accuracy and processing speeds of up to 30 FPS on phone-camera input, while improving performance under poor lighting, low-resolution imagery, multiple viewing angles, and crowded scenes.',
        'Deployed the capability for multiple startup customers through the SaaS platform and as a standalone CCTV solution for a police department.',
      ],
      stack: [
        'Python',
        'PyTorch',
        'TensorFlow',
        'OpenCV',
        'MongoDB',
        'Redis',
        'Nginx',
        'Milvus',
        'Kafka',
        'Pulsar',
        'Docker',
        'Jenkins',
      ],
    },
  ],
  projects: [
    {
      title: 'Horizon Blog',
      githubUrl: 'https://github.com/connortran216/horizon-blog',
      description:
        'Personal blog application built with React, TypeScript, and Chakra UI, paired with a Go backend that uses clean architecture, JWT authentication, PostgreSQL, media upload support, and API documentation. The project includes rich text editing, search and filtering, a contact form, and technical documentation.',
      stack: [
        'React',
        'TypeScript',
        'Chakra UI',
        'React Router',
        'Milkdown',
        'Vite',
        'Go',
        'Gin',
        'GORM',
        'PostgreSQL',
        'JWT',
        'Swagger',
        'MinIO',
        'Meilisearch',
        'Docker',
      ],
    },
    {
      title: 'Measurement of fetal head circumference based deep learning on 2D ultrasound images',
      period: '12/2020 - 04/2021',
      githubUrl: 'https://github.com/connortran216/Fetal-Head-Circumferences-HC18',
      publicationUrl:
        'http://vap.ac.vn/Portals/0/TuyenTap/2021/12/22/1ecec417207345d595e011cb434f7fe8/20_FAIR2021_paper_139.pdf',
      description:
        'Built a segmentation system to automatically measure fetal head circumference on 2D ultrasound images. In the HC18 grand challenge, the system achieved a mean absolute difference of 7.15 mm with a standard deviation of 4.33.',
      stack: ['Mask RCNN', 'OpenCV', 'Ellipse approximation of Ramanujan'],
    },
    {
      title: 'Facial Recognition',
      period: '09/2019',
      githubUrl: 'https://github.com/connortran216/Attendace-Cheking-using-Facenet-and-MTCNN',
      description:
        'Built a real-time facial recognition pipeline using MTCNN for face detection, FaceNet for feature extraction, and an SVM classifier for identity classification. The model achieved approximately 90% accuracy.',
      stack: ['MTCNN', 'FaceNet', 'OpenCV', 'SORT'],
    },
  ],
  education: [
    {
      school: 'Ton Duc Thang University',
      degree: 'Bachelor of Science in Computer Science',
      period: '2017 - 2021',
      details: [
        'GPA: 7.53/10.',
        'Relevant coursework: Linear Algebra, Statistic & Probability, Calculus, Machine Learning (GPA: 9.3), Artificial Intelligence (GPA: 8.1).',
        'Strengths: Mathematics, Machine Learning, and Deep Learning.',
      ],
    },
  ],
}
