import { FaArrowUpRightFromSquare, FaDownload, FaGithub, FaLinkedin } from 'react-icons/fa6'
import { CvProfile } from './cv.types'

export const cvProfile: CvProfile = {
  name: 'Tran Tuan Canh',
  title: 'Backend Engineer',
  location: 'Ho Chi Minh City, Vietnam',
  email: 'canhtran210699@gmail.com',
  summary:
    'I am a Backend Engineer focused on building reliable, scalable, and maintainable systems that solve real product and engineering problems.\n\nI enjoy working on backend architecture, distributed systems, data-intensive applications, and production workflows where performance, reliability, clean abstractions, and product impact all matter. I like turning complex engineering problems into practical solutions by understanding the problem deeply, breaking it down clearly, and making thoughtful trade-offs.\n\nBeyond traditional backend engineering, I am especially interested in AI-powered engineering workflows and how AI can help teams design systems, write better technical specifications, build internal tools, and improve developer productivity.\n\nFor me, engineering is not only about writing code. It is about designing systems that can evolve over time, improving them continuously, and pushing myself to become a stronger engineer.',
  competencies: [
    {
      title: 'Backend',
      items: ['Python', 'Django', 'Django Ninja', 'Django REST Framework', 'FastAPI'],
    },
    {
      title: 'Data & Messaging',
      items: ['Kafka', 'PostgreSQL', 'Redis', 'OpenSearch', 'ClickHouse', 'Redshift'],
    },
    {
      title: 'Workflow & Processing',
      items: ['Dagster', 'Scala', 'Flink'],
    },
    {
      title: 'Platform',
      items: ['Docker', 'Helm', 'Kubernetes', 'AWS'],
    },
    {
      title: 'Architecture',
      items: [
        'API design',
        'Validation',
        'Pydantic',
        'Modular service structure',
        'Service-layer patterns',
      ],
    },
    {
      title: 'Shared Capabilities',
      items: ['Search', 'Data synchronization', 'Feature flags', 'Business-calendar logic'],
    },
    {
      title: 'Delivery',
      items: [
        'Asynchronous processing',
        'Outbox-style publishing',
        'Cross-functional backend delivery',
      ],
    },
  ],
  links: [
    {
      label: 'Export PDF',
      icon: FaDownload,
    },
    {
      label: 'Blog',
      href: 'https://blog.connortran.io.vn/',
      icon: FaArrowUpRightFromSquare,
      isExternal: true,
    },
    {
      label: 'GitHub',
      href: 'https://github.com/connortran216',
      icon: FaGithub,
      isExternal: true,
    },
    {
      label: 'LinkedIn',
      href: 'https://www.linkedin.com/in/c%E1%BA%A3nh-tr%E1%BA%A7n-tu%E1%BA%A5n-b57564162/',
      icon: FaLinkedin,
      isExternal: true,
    },
    {
      label: 'Contact',
      to: '/contact',
      icon: FaArrowUpRightFromSquare,
    },
  ],
  experience: [
    {
      company: 'Parcel Perform',
      role: 'Backend Engineer',
      period: '2023 - Present',
      highlights: [
        'Designed, built, and maintained backend APIs for shipment analytics, alerting, and automated insight generation, covering shipment-performance querying and reporting, rule-based alert evaluation against configurable thresholds, and insight generation from operational metrics.',
        'Built and maintained real-time SLA metric processing on live parcel events using Flink, Kafka, and outbox-style publishing, helping operations teams and merchants monitor shipment health and carrier performance more reliably.',
        'Improved backend quality across service repositories through code review, test design, and implementation standards, maintaining above 90% test coverage across related repositories.',
        'Contributed to the migration from Django REST Framework to Django Ninja, improving API maintainability, schema clarity, validation, and developer experience.',
        'Created Claude Code skills and agents to accelerate custom SLA implementation while preserving quality through workflow guardrails, review steps, and reusable implementation patterns.',
        'Created Claude Code workflows for epic handling and CI follow-up from Jira tickets, reducing manual coordination effort and improving delivery accuracy across the squad.',
      ],
      stack: [
        'Python',
        'Django',
        'Django Ninja',
        'Django REST Framework',
        'FastAPI',
        'Kafka',
        'PostgreSQL',
        'Redis',
        'OpenSearch',
        'ClickHouse',
        'Redshift',
        'Dagster',
        'Scala',
        'Flink',
        'Docker',
        'Helm',
        'Kubernetes',
        'AWS',
      ],
    },
    {
      company: 'Think Prompt',
      role: 'Backend Engineer Team Lead',
      period: '2023',
      productionUrl: 'https://bizchat.thinkprompt.com/',
      highlights: [
        'Designed and built the backend foundation for a ChatGPT-like business chatbot platform, covering system architecture, RESTful APIs, service structure, and infrastructure setup.',
        'Led backend delivery across AI integration, application APIs, storage, caching, and deployment concerns, helping turn an early product concept into a production-ready service.',
        'Coordinated backend priorities, clarified technical direction, and translated product and AI requirements into implementable tasks for the engineering team.',
        'Improved team output quality through code review, debugging support, error-handling guidance, and mentoring for junior developers.',
      ],
      stack: [
        'Python',
        'FastAPI',
        'Hypercorn',
        'LangChain',
        'Postgres',
        'MongoDB',
        'MinIO',
        'Redis',
        'Nginx',
        'Milvus',
        'Docker',
        'GitLab CI',
        'AWS',
        'On-premise infrastructure',
      ],
    },
    {
      company: 'SSSMarket',
      role: 'Backend Engineer Team Lead',
      period: '01/2022 - 01/2023',
      productionUrl: 'https://www.sssmarket.vn/',
      highlights: [
        'Designed and built backend services for an e-commerce platform, covering RESTful APIs, service architecture, infrastructure setup, and integration with product workflows.',
        'Led backend implementation across product, search, storage, caching, and deployment capabilities, supporting feature delivery across the application.',
        'Improved backend quality and maintainability through code review, technical guidance, and shared engineering standards for the team.',
        'Strengthened platform stability by identifying and resolving performance and security issues in the backend stack.',
        'Communicated delivery progress, risks, and technical trade-offs with the CTO and stakeholders to keep implementation aligned with business priorities.',
      ],
      stack: [
        'Python',
        'FastAPI',
        'Hypercorn',
        'SQLAlchemy',
        'Postgres',
        'MongoDB',
        'MinIO',
        'Redis',
        'Nginx',
        'Milvus',
        'Solr',
        'Docker',
        'GitLab CI',
        'AWS',
        'On-premise infrastructure',
      ],
    },
    {
      company: 'Dai Phat Solutions',
      role: 'AI Engineer',
      period: '12/2020 - 01/2022',
      productionUrl: 'https://www.dps.com.vn/vi/products/doanhnghiep#',
      highlights: [
        'Built real-time facial recognition capabilities for attendance and CCTV surveillance workflows, supporting practical computer-vision use cases in enterprise environments.',
        'Developed and improved AI pipelines across face detection, recognition, tracking, and model integration.',
        'Translated AI research and experiment results into product improvements, improving recognition accuracy, reliability, and operational fit.',
        'Worked with cross-functional stakeholders to gather requirements, validate system behavior, and align model improvements with real user needs.',
      ],
      stack: [
        'Python',
        'PyTorch',
        'TensorFlow',
        'OpenCV',
        'MongoDB',
        'Redis',
        'Nginx',
        'Milvus',
        'Kafka',
        'Pulsar',
        'Docker',
        'Jenkins',
      ],
    },
  ],
  projects: [
    {
      title: 'Horizon Blog',
      githubUrl: 'https://github.com/connortran216/horizon-blog',
      description:
        'Personal blog application built with React, TypeScript, and Chakra UI, paired with a Go backend that uses clean architecture, JWT authentication, PostgreSQL, media upload support, and API documentation. The project includes rich text editing, search and filtering, a contact form, and technical documentation.',
      stack: [
        'React',
        'TypeScript',
        'Chakra UI',
        'React Router',
        'Milkdown',
        'Vite',
        'Go',
        'Gin',
        'GORM',
        'PostgreSQL',
        'JWT',
        'Swagger',
        'MinIO',
        'Meilisearch',
        'Docker',
      ],
    },
    {
      title: 'Measurement of fetal head circumference based deep learning on 2D ultrasound images',
      period: '12/2020 - 04/2021',
      githubUrl: 'https://github.com/connortran216/Fetal-Head-Circumferences-HC18',
      publicationUrl:
        'http://vap.ac.vn/Portals/0/TuyenTap/2021/12/22/1ecec417207345d595e011cb434f7fe8/20_FAIR2021_paper_139.pdf',
      description:
        'Built a segmentation system to automatically measure fetal head circumference on 2D ultrasound images. In the HC18 grand challenge, the system achieved a mean absolute difference of 7.15 mm with a standard deviation of 4.33.',
      stack: ['Mask RCNN', 'OpenCV', 'Ellipse approximation of Ramanujan'],
    },
    {
      title: 'Facial Recognition',
      period: '09/2019',
      githubUrl: 'https://github.com/connortran216/Attendace-Cheking-using-Facenet-and-MTCNN',
      description:
        'Built a real-time facial recognition pipeline using MTCNN for face detection, FaceNet for feature extraction, and an SVM classifier for identity classification. The model achieved approximately 90% accuracy.',
      stack: ['MTCNN', 'FaceNet', 'OpenCV', 'SORT'],
    },
  ],
  education: [
    {
      school: 'Ton Duc Thang University',
      degree: 'Bachelor of Science in Computer Science',
      period: '2017 - 2021',
      details: [
        'GPA: 7.53/10.',
        'Relevant coursework: Linear Algebra, Statistic & Probability, Calculus, Machine Learning (GPA: 9.3), Artificial Intelligence (GPA: 8.1).',
        'Strengths: Mathematics, Machine Learning, and Deep Learning.',
      ],
    },
  ],
}
